@startuml
!pragma useVerticalIf on
start
:User enters sort command;
if () then ([else])
  :Error: Invalid command format;
  stop
( [Both Field and Sorting Order provided]) elseif () then ([else])
  :Error: Invalid command format;
  stop
else ( [Valid Field and Valid Sorting Order provided])

endif
  :Sort Command successfully executes.The displayed list of
students is updated to be in sorted order of the provided field
in the specified order;
stop

@enduml
